[development]
    [development.bot]
        token =
        slip_updates =
    [development.psql]
        host =
        port =
        user =
        password =
        database =
    [development.redis]
        redis_host =
        redis_port =
        redis_database =
        redis_password =
