[work]
    [work.tgbot]
        token =
        slip_updates =
    [work.psql]
        host =
        port =
        user =
        password =
        database =
    [work.redis]
        redis_host =
        redis_port =
        redis_database =
        redis_password =
