[work]
    [work.tgbot]
        token = # String type
        slip_updates = # Bool type
    [work.psql]
        host = # String type
        port = # Integer type
        user = # String type
        password = # String type
        database = # Integer type
    [work.redis]
        redis_host = # String type
        redis_port = # Intger type
        redis_database = # Intger type
        redis_password = # String type

[test]
    [test.tgbot]
        token = # String type
        slip_updates = # Bool type
    [test.psql]
        host = # String type
        port = # Integer type
        user = # String type
        password = # String type
        database = # Integer type
    [test.redis]
        redis_host = # String type
        redis_port = # Intger type
        redis_database = # Intger type
        redis_password = # String type
